### ISSUE TITLE
oneplus6

### ISSUE THREAD

**Issue by junocomp** [droidian-releng/droidian-installer#1]
Please provide an installer for oneplus6

**Comment by erikinkinen** [comment]
I do not know of an adaptation for the OP6. If you know and you can test it, you're welcome to open a PR at https://github.com/droidian-devices/installer-configs .

**Comment by FakeShell** [comment]
as theres no port for op6 at least by us and no one has provided any proper port for that device i guess we can close this issue for now. maybe someone can step up and add that device one day.

**Comment by junocomp** [comment]
Any chance to add it now? 

https://github.com/FakeShell/droidian-oneplus6/releases
