### ISSUE TITLE
image download 404 error

### ISSUE THREAD

**Issue by develperbayman** [droidian-releng/droidian-installer#10]
as the title on downloading device image gets 404 error miatoll

**Comment by stele95** [comment]
Can confirm the same is happening to me, also the link in the `Manual installation` section [here](https://devices.droidian.org/#/devices/miatoll#Droidian_installation) is returning `404`

**Comment by FakeShell** [comment]
@g7 mind taking a look at the image router

**Comment by FakeShell** [comment]
should be ok now
