### ISSUE TITLE
redmi note 7

### ISSUE THREAD

**Issue by Staryvyr** [droidian-releng/droidian-installer#2]
During installation of droidian phosh (using the .deb - package) I've got the following error (copy & paste from the
terminal's log --- the same information was shown in the GUI of that I have not taken a photo):

error: Error: fastboot:flash: Error: Flashing failed: {"error":{"code":1},"stder
r":"fastboot: error: cannot load '/home/jelen/.cache/droidian/lavender/firmware/
unpacked_droidian/data/vendor.img': No such file or directory"}
stack trace: Error: Flashing failed: {"error":{"code":1},"stderr":"fastboot: err
or: cannot load '/home/jelen/.cache/droidian/lavender/firmware/unpacked_droidian
/data/vendor.img': No such file or directory"}
    at /opt/droidian-installer/resources/app.asar.unpacked/node_modules/promise-
android-tools/lib/module.cjs:1121:15
    at /opt/droidian-installer/resources/app.asar.unpacked/node_modules/promise-
android-tools/node_modules/cancelable-promise/dist/CancelablePromise.js:27:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
)

After using the "Ignoring the error"-option I've got immediately the message that the installation was 
successfull, which I really could not believe because the bar of progress before has been still far
from the 100%.

After booting of the device droidian phosh was starting. However I have no clue if the problems
of any of the functions I have (camera is not working, waydroid cannot start after installation) has
anything to do with an incomplete installation.

So pls have a look,
M.

**Comment by erikinkinen** [comment]
@FakeShell , I guess the installer configs have an error?

**Comment by FakeShell** [comment]
i tested it with ubports installer it should just work here as well? @erikinkinen maybe you removed something that you shouldnt have?
camera works on latest kernel and the vendor in in the installer

https://github.com/ubports/installer-configs/blob/master/v2/devices/lavender.yml#L66

**Comment by erikinkinen** [comment]
@FakeShell the configs download vendor only if you install Ubuntu Touch.

**Comment by Staryvyr** [comment]
I did the installing process for several times (without varying anything) --- sometimes the camera is
working and sometimes not. Waydroid however was never able to start -- no matter how much time
I give, the first launch process never finishes.

**Comment by FakeShell** [comment]
waydroid is a known issue
https://github.com/droidian-images/droidian/releases/tag/droidian%2Fbookworm%2F26
listed here as well
you can try the new camera app: `sudo apt install droidian-camera` and try that. its not yet the default app but it soon will be

**Comment by Staryvyr** [comment]
Uhh, that is great, thanks!

**Comment by erikinkinen** [comment]
This issue is due to the installer now using official Droidian images which do not ship their own vendor. @FakeShell promised to fix the configs at https://github.com/ubports/installer-configs and https://github.com/droidian-devices/installer-configs .

**Comment by Staryvyr** [comment]
Thanks a lot!

A last (probably naive question): Does this early abortion of the installation process mean that anything on my phone
could be mis- or even not configured/installed ? (I have not found any other problems so far, but that does not
mean that such problems cannot exist e.g. security issues).

**Comment by erikinkinen** [comment]
It seems it failed to flash vendor.img. I am not sure of this particular case, but a common reason to include a vendor.img in the installer would be that a modified vendor.img is required for full functionality instead of the stock one.

@FakeShell gave this link for downloading the vendor.img: https://www.androidfilehost.com/?fid=10763459528675594236

After downloading and extracting, you should be able to flash it using fastboot through command-line: `fastboot flash vendor vendor.img` (phone in fastboot-mode)

**Comment by Staryvyr** [comment]
Ok, I did that. Thanks a lot again!

**Comment by FakeShell** [comment]
should be fixed
https://github.com/droidian-devices/installer-configs/pull/1
