### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by bokf** [droidian-releng/droidian-installer#4]
Trying to install droidian on a Volla Phone 22 I get following Error message:
https://images.droidian.org/droidian/nightly/arm64/volla/image-fastboot-mimameid.zip
Error: Request failed with status code 404
It seams, that the image is not at this location. Could you check the link?

**Comment by FakeShell** [comment]
refer to https://github.com/droidian-images/droidian/issues/11

**Comment by erikinkinen** [comment]
I dropped it from configs: https://github.com/droidian-devices/installer-configs/commit/590bc2a3ae19e95eeb3acbdb6bae410c26369db2

I hope I will be able to fix it at some point. I will have to rebase the port to Halium 12 anyways due to a hardware change in a newer revision of the phone.
