### ISSUE TITLE
The droidian installer still uses ubports installer icon

### ISSUE THREAD

**Issue by sanathusk** [droidian-releng/droidian-installer#5]
The droidian installer still uses ubports installer launcher icon.Attached the screenshot of the same.
![Screenshot 2023-09-24 at 12 33 55 PM](https://github.com/droidian-releng/droidian-installer/assets/19380158/49440735-747d-4696-9bca-639fce7d210f)

**Comment by sanathusk** [comment]
raised a draft PR for the same https://github.com/droidian-releng/droidian-installer/pull/6

**Comment by erikinkinen** [comment]
This has been fixed.
