### ISSUE TITLE
Snap/Flathub

### ISSUE THREAD

**Issue by junocomp** [droidian-releng/droidian-installer#9]
Droidian Installer needs to be accessible from Snap or Flathub, otherwise it will just live secretly on Github

**Comment by erikinkinen** [comment]
That makes sense.

I think it would be also a good idea to have a hyperlink in https://droidian.org/ for downloading it.

What do you think, @FakeShell ?

**Comment by junocomp** [comment]
I see there is a snap config on the repo, any chance to publish it?

https://github.com/droidian-releng/droidian-installer/tree/master/snap

**Comment by FakeShell** [comment]
https://snapcraft.io/droidian-installer
added to snapcraft, cannot be added to flathub because of limitations with fastboot. closing.
